content:
  - name: pages
    label: Страницы
    icon: book-open
    path: src/pages
    type: collection
    view:
      fields: [ title, published, date ]
    fields:
      - name: published
        label: Published
        type: boolean
      - name: title
        label: Заголовок
        type: string
      - name: permalink
        label: URL
        type: string
      - name: date
        label: Дата создания
        type: date
      - name: body
        label: Содержание
        type: rich-text
